---
abstract: 'locate Perl Modules in Debian repositories'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  Module::Build::SysPath: 0.13
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
  Module::Build::SysPath: 0.13
generated_by: 'Module::Build version 0.3603'
keywords:
  - debian
  - perl
  - modules
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Debian-Apt-PM
provides:
  Debian::Apt::PM:
    file: lib/Debian/Apt/PM.pm
    version: 0.03
  Debian::Apt::PM::SPc:
    file: lib/Debian/Apt/PM/SPc.pm
    version: 0.02
requires:
  AptPkg::Config: 0
  CPAN: 0
  CPAN::Patches: 0
  CPAN::Version: 0
  Carp: 0
  Dpkg::Version: 0
  File::Basename: 0
  File::Copy: 0
  File::Find::Rule: 0
  File::HomeDir: 0
  File::Path: 2.01
  File::Temp: 0
  File::is: 0
  Getopt::Long: 0
  IO::Any: 0
  IO::Uncompress::Bunzip2: 0
  JSON::Util: 0
  LWP::Simple: 0
  List::MoreUtils: 0
  Module::Build::ModuleInfo: 0
  Moose: 0
  Parse::Deb::Control: 0.03
  Pod::Usage: 0
  Storable: 0
resources:
  bugtracker: http://github.com/jozef/Debian-Apt-PM/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jozef/Debian-Apt-PM.git
version: 0.03
